name = "schematic-example"
author = "brooswit-factory"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a969e26a4d59c079136721c9afc1ba58e67692470412d9c33ee43db9548ab005"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
